[tool.poetry]
name = "p-preparations"
version = "0.1.0"
description = "Common questions"
authors = ["Viachaslau Kazakou <sly.kazakoff@epam.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
asyncpg = "^0.29.0"
python-json-logger = "^2.0.7"
uvloop = "^0.19.0"
yarl = "^1.9.2"
attrs = "23.1.0"
typing-extensions = "^4.6.3"
cchardet = "^2.1.7"
requests = "==2.31.0"
httpx = "^0.25.2"
beautifulsoup4 = "^4.12.2"
structlog = "^23.2.0"


[tool.poetry.group.dev.dependencies]
freezegun = "^1.2.2"
pytest = "^7.4.0"
pytest-mock = "^3.11.1"
pytest-factoryboy = "^2.5.1"
pytest-asyncio = "^0.21.1"
flake8 = "^5.0.4"
isort = "^5.10.1"
tox = "^3.26.0"
black = "^22.8.0"
mypy = "^0.981"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 120
target-version = ['py310']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
)
'''