"""init table

Revision ID: fea64fa1fb47
Revises: 
Create Date: 2024-01-19 13:29:34.193706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fea64fa1fb47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_id', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_id_ip_id'), 'blocked_id', ['ip_id'], unique=False)
    op.create_table('description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['blocked_id.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('description')
    op.drop_index(op.f('ix_blocked_id_ip_id'), table_name='blocked_id')
    op.drop_table('blocked_id')
    # ### end Alembic commands ###
